/**
 * ITimeoutHandler.h
 *
 *   Version: 2015-01-23
 *    Author: Jaco ter Braak, University of Twente.
 * Copyright: University of Twente, 2015-2019
 *
 ************************************************************
 *                                                          *
 **                 DO NOT EDIT THIS FILE                  **
 ***         YOU DO NOT HAVE TO LOOK IN THIS FILE         ***
 **** IF YOU HAVE QUESTIONS PLEASE DO ASK A TA FOR HELP  ****
 *****                                                  *****
 ************************************************************
 */

#ifndef ITIMEOUTHANDLER_H_
#define ITIMEOUTHANDLER_H_

namespace framework {
    class ITimeoutHandler {
    public:
        /**
         * Method for timeout callbacks
         */
        virtual void TimeoutElapsed(ssize_t) = 0;

    };
} /* namespace framework */
#endif /* ITIMEOUTHANDLER_H_ */
