/**
 * NetworkLayer.h
 *
 *   Version: 2015-01-14
 *    Author: Jaco ter Braak, University of Twente.
 * Copyright: University of Twente, 2015-2019
 *
 ************************************************************
 *                                                          *
 **                 DO NOT EDIT THIS FILE                  **
 ***         YOU DO NOT HAVE TO LOOK IN THIS FILE         ***
 **** IF YOU HAVE QUESTIONS PLEASE DO ASK A TA FOR HELP  ****
 *****                                                  *****
 ************************************************************
 */

#ifndef NETWORKLAYER_H_
#define NETWORKLAYER_H_

#include <sys/types.h>
#include <stdlib.h>
#include <cstdint>
#include <vector>
#include "DRDTChallengeClient.h"

namespace framework {

    class NetworkLayer {
    public:
        NetworkLayer(DRDTChallengeClient *drdtclient);
        virtual ~NetworkLayer();
        void sendPacket(std::vector<int32_t> packet);
        bool receivePacket(std::vector<int32_t> *packet);
    private:
        DRDTChallengeClient* challengeClient;
    };

} /* namespace framework */

#endif /* NETWORKLAYER_H_ */
