/**
 * NetworkLayer.cpp
 *
 *   Version: 2015-01-14
 *    Author: Jaco ter Braak, University of Twente.
 * Copyright: University of Twente, 2015-2019
 *
 ************************************************************
 *                                                          *
 **                 DO NOT EDIT THIS FILE                  **
 ***         YOU DO NOT HAVE TO LOOK IN THIS FILE         ***
 **** IF YOU HAVE QUESTIONS PLEASE DO ASK A TA FOR HELP  ****
 *****                                                  *****
 ************************************************************
*/

#include "NetworkLayer.h"

namespace framework {

    NetworkLayer::NetworkLayer(DRDTChallengeClient *drdtclient) {
        this->challengeClient = drdtclient;
    }

    NetworkLayer::~NetworkLayer() {
    }

    void NetworkLayer::sendPacket(std::vector<int32_t> packet) {
        this->challengeClient->sendPacket(packet);
    }

    bool NetworkLayer::receivePacket(std::vector<int32_t> *packet) {
        return this->challengeClient->receivePacket(packet);
    }

} /* namespace framework */
