/**
 * Utils.h
 *
 *   Version: 2016-02-11
 *    Author: Jaco ter Braak & Frans van Dijk, University of Twente.
 * Copyright: University of Twente, 2015-2019
 *
 ************************************************************
 *                                                          *
 **                 DO NOT EDIT THIS FILE                  **
 ***         YOU DO NOT HAVE TO LOOK IN THIS FILE         ***
 **** IF YOU HAVE QUESTIONS PLEASE DO ASK A TA FOR HELP  ****
 *****                                                  *****
 ************************************************************
 */

#ifndef UTILS_H_
#define UTILS_H_

#include <sys/types.h>
#include <vector>
#include <fstream>
#include <string>
#include <sstream>
#include "timer.h"
#include "IRDTProtocol.h"
#include "ITimeoutEventHandler.h"

namespace framework {
    std::vector<int32_t> getFileContents(std::string id);
    void setFileContents(std::vector<int32_t> fileContents, std::string id, std::string file_timestamp);
    void SetTimeout(long millisecondsTimeout, ITimeoutEventHandler* instance, int32_t tag);
    int test();
} /* namespace framework */

#endif /* UTILS_H_ */
